services:
  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: smart-milk/users-service:1.1
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: "3000"
      ALLOWED_ORIGINS: http://localhost:5173
      JWT_SECRET: please_change_me

      # מתחברים ל-DB שרץ בשורש על 3307 דרך ה-Host:
      DB_HOST: host.docker.internal
      DB_PORT: "3307"
      DB_NAME: users_db
      DB_USER: milkuser
      DB_PASS: Milk123!

      # אם יש לך גם משתני סשן – הוסיפי פה
      # SESSION_COOKIE_NAME: sid
      # SESSION_TTL_HOURS: "24"
      # SESSION_SAMESITE: Lax
      # SESSION_SECURE: "false"
    restart: unless-stopped
