apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: smart-milk
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass123
  MYSQL_DATABASE: users_db
  MYSQL_USER: milkuser
  MYSQL_PASSWORD: Milk123!
