apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: smart-milk
data:
  001_users.sql: |
    CREATE DATABASE IF NOT EXISTS users_db;
    USE users_db;

    CREATE TABLE IF NOT EXISTS users (
      id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      username   VARCHAR(64)  NOT NULL UNIQUE,
      password   VARCHAR(255) NOT NULL,
      full_name  VARCHAR(255) NOT NULL,
      email      VARCHAR(255) NOT NULL UNIQUE,
      phone      VARCHAR(32)  NULL,
      device_id  VARCHAR(50)  NOT NULL UNIQUE,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    INSERT IGNORE INTO users (username,password,full_name,email,device_id)
    VALUES ('demo_user1','demo_pass','Demo User','demo_user1@example.com','device1');

  002_user_stats.sql: |
    USE users_db;
    CREATE TABLE IF NOT EXISTS user_stats (
      user_id                 INT UNSIGNED NOT NULL,
      container_id            VARCHAR(128) NULL,
      current_amount_g        FLOAT        NULL,
      avg_daily_consumption_g FLOAT        NULL,
      cups_left               FLOAT        NULL,
      percent_full            FLOAT        NULL,
      expected_empty_date     DATE         NULL,
      PRIMARY KEY (user_id),
      CONSTRAINT fk_stats_user FOREIGN KEY (user_id) REFERENCES users(id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
