apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: smart-milk
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
  namespace: smart-milk
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 1Gi } }

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: smart-milk
spec:
  selector: { app: mosquitto }
  ports:
    - port: 1883
      targetPort: 1883

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: smart-milk
spec:
  replicas: 1
  selector: { matchLabels: { app: mosquitto } }
  template:
    metadata:
      labels: { app: mosquitto }
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          ports: [{ containerPort: 1883 }]
          volumeMounts:
            - { name: cfg,  mountPath: /mosquitto/config }
            - { name: data, mountPath: /mosquitto/data }
      volumes:
        - name: cfg
          configMap:
            name: mosquitto-config
            items: [{ key: mosquitto.conf, path: mosquitto.conf }]
        - name: data
          persistentVolumeClaim: { claimName: mosquitto-pvc }
